### ISSUE TITLE
No support for ATOM feed

### ISSUE THREAD

**Issue by izikeros** [dhvcc/rss-parser#1]
Tried to parse xml from: `https://stackoverflow.com/feeds/tag/jupyter` and module failed on trying to get version from RSS.

**Comment by dhvcc** [comment]
Hey @izikeros, seems that the problem is that this is `ATOM` feed, not `RSS`
However, I will try to add atom support in next release

**Comment by dhvcc** [comment]
Hey, just thinking that it would be nice to migrate to xml schemas for validation and xpath for extraction. This would allow supporting more standarts like ATOM. I don't have time to do it in near future, but PRs are welcome :)
