### ISSUE TITLE
Crash when there is no description_soup

### ISSUE THREAD

**Issue by Thewildweb** [dhvcc/rss-parser#18]
Hia,

I have been playing around with your rss_parser and I noticed that when a RSS does not have a description element in an item it crashes.

Like with this feed: https://www.dutchcowboys.nl/feed/rss.

Is this intentional?

Kind regards,

Erik

**Comment by dhvcc** [comment]
Hello! Thanks for using the library. I think there were similar issues raised and answered, but can't find one.

Anyways, the thing is that the "description" field is required for RSS spec. It would make sense to add "lite" mode when all of the fields are optional, but I'm limited in time for now. However, the more people need it the faster it will be implemented.

You just may submit a patch with making them optional, or I can do it if this is important.

**Comment by dhvcc** [comment]
Oh, yeah it was not an issue, but a PR #17 
You may want to check out a discussion there

**Comment by dhvcc** [comment]
Closing as inactive
