### ISSUE TITLE
It rss-parser support multiple source parse?

### ISSUE THREAD

**Issue by ghost** [dhvcc/rss-parser#2]
Hello. I'm currently make my own RSS parsers project with MULTIPLE source(url). It your library support for parse multiple source?

**Comment by dhvcc** [comment]
@buinguyenhoangtho no it does not
The constructor only accepts 1 url as an argument

**Comment by ghost** [comment]
Ah yes thanks for information
 Here another thing , let said i want to get feed title( not items ) 
Here example :
I want to get " astronomy-google news" like this example.  Anyway to get it ? Https://news.google.com/rss/search?cf=all&hl=en-US&pz=1&q=astronomy&gl=US&ceid=US:en

**Comment by dhvcc** [comment]
> Ah yes thanks for information
> Here another thing , let said i want to get feed title( not items )
> Here example :
> I want to get " astronomy-google news" like this example. Anyway to get it ? [Https://news.google.com/rss/search?cf=all&hl=en-US&pz=1&q=astronomy&gl=US&ceid=US:en](Https://news.google.com/rss/search?cf=all&hl=en-US&pz=1&q=astronomy&gl=US&ceid=US:en)

Title is parsed too
https://github.com/dhvcc/rss-parser/blob/1fbdc34103a7b81a806280589c8215b5f924faa8/rss_parser/models.py#L12

**Comment by buinguyenhoangtho** [comment]
![12](https://user-images.githubusercontent.com/76900905/109910625-211a8400-7cdb-11eb-996f-eb5dcb47f1f5.png)
I was trying deploy to heroku today but i can't deploy witth requirements.txt. 
![image](https://user-images.githubusercontent.com/76900905/109910707-545d1300-7cdb-11eb-98a7-917e6a2a49c2.png)
This is my requirements.txt
