### ISSUE TITLE
Link in the text

### ISSUE THREAD

**Issue by Phantomik** [dhvcc/rss-parser#25]
If there is a link with a keyword in the text, then the link disappears, only the keyword remains, can I do something about it?

**Comment by dhvcc** [comment]
Could you please send an example of this RSS feed?

**Comment by Phantomik** [comment]
https://philthyboys.ru/data/rss
![image](https://user-images.githubusercontent.com/7623387/163658144-e2f43104-aa29-48cb-85b2-e6e8f4699d94.png)

**Comment by dhvcc** [comment]
> https://philthyboys.ru/data/rss
> ![image](https://user-images.githubusercontent.com/7623387/163658144-e2f43104-aa29-48cb-85b2-e6e8f4699d94.png)
> 

I'll check this one today

**Comment by BBArikL** [comment]
I think it is being discarded by bs4 because <link> is a tag and bs4 only gives back the text between the <descritption> tag. Looking at the documentation, it should give back the raw text with tags and I do not see anywhere in the code where the rss parser deletes them. Also @dhvcc , since January you did not do a release, I would appreciate one on Pypi when this issue is resolved! 👍  I did not even recognise that it did not update because I kept using my hacky workaround in my code 😅

**Comment by dhvcc** [comment]
> I think it is being discarded by bs4 because <link> is a tag and bs4 only gives back the text between the <descritption> tag. Looking at the documentation, it should give back the raw text with tags and I do not see anywhere in the code where the rss parser deletes them. Also @dhvcc , since January you did not do a release, I would appreciate one on Pypi when this issue is resolved! 👍  I did not even recognise that it did not update because I kept using my hacky workaround in my code 😅 

Yeah, will do one for sure. Thanks for using the package

**Comment by dhvcc** [comment]
Hey @Phantomik. As far as I can see - these are not valid "tags" in RSS, hence, they are treated as text and escaped. You can try to unescape them if you really want too, but then you'd have to work with bs4 manually. Something like this could do the trick (note, that this is a mock up of a code and I did not test it myself)
```python3
from xml.sax.saxutils import unescape
from bs4 import BeautifulSoup
...
feed = parser.parse()
# Iteratively print feed items
for item in feed.feed:
    soup = BeautifulSoup(unescape(item.description))
    print(soup.find_all('a'))
```

**Comment by dhvcc** [comment]
Please, make sure to close the issue if you fell like it was resolved. I'll push a release after that @BBArikL

**Comment by Phantomik** [comment]
Thank you @dhvcc . The guys and I decided to leave it as it is for now. And write your own parser so that there are links and pictures. Later I will check your guess and write.

**Comment by BBArikL** [comment]
So, while looking back at the code to make it ready for the next release I remembered that even if bs4 does strip out html tags (<a> with href and <img>), the parser does make a search for them so it wont appear in the description itself, but it should appear as one of the values of the attribute `description_links`. But if you really want to know the text that was marked by the tags then @dhvcc 's example could work. 
![Screenshot_20220422_224552](https://user-images.githubusercontent.com/55418469/164868969-fa64fbc8-fb48-4e78-9ba7-7a056e07e113.png)
