### ISSUE TITLE
lxml requirements too strict

### ISSUE THREAD

**Issue by RadioErewan** [dhvcc/rss-parser#3]
Installing rss-parser on Windows results in uninstallation of lxml4.6.3 and reinstall of 4.5.2 (which leads to codepage errors on my python 3.9, rollback to 4.6.3 and aborted rss-parser install).
Changing requirements in wheel to 4.6.3 fixes problem localy.

**Comment by dhvcc** [comment]
Do you use virtual environment? You use python 3.9, am I correct?

**Comment by RadioErewan** [comment]
Yes, virtual environment and Python 3.9. I tried to skip venv and the result is the same.

**Comment by dhvcc** [comment]
Hey, @RadioErewan , I've updated the requirements, so now everything sohuld work

It's latest release `2.2` a6bdb7867a5dda02b2c724fe0bccdb701144832e, already on `PyPi`
