### ISSUE TITLE
Release rss-parser 0.2.4

### ISSUE THREAD

**Issue by BBArikL** [dhvcc/rss-parser#30]
Its been a while since rss-parser has been considered "feature-complete" and the checks for edge cases in non-conventional rss has been made, is it possible to have a release in the near future?

**Comment by dhvcc** [comment]
Hi, sorry for the delay of the release. Let me create a couple of tests so we can at least test this release and the future ones. Will do a release today

**Comment by BBArikL** [comment]
You can use the code that I left on the comments of pr #26 for testing if you want :)

**Comment by dhvcc** [comment]
Hey, should've notified you sooner - it's released
