### ISSUE TITLE
Error when parsing rss files

### ISSUE THREAD

**Issue by DimaDDM** [dhvcc/rss-parser#34]
Crash when trying parsing resources like investing.com
```
Traceback (most recent call last):
  File "/rss_news.py", line 121, in __get_investing_news
    entities = parser.parse()
  File "venv/lib/python3.10/site-packages/rss_parser/_parser.py", line 89, in parse
    "version": main_soup.rss.get("version"),
AttributeError: 'NoneType' object has no attribute 'get'
```

"https://ru.investing.com/rss/news_1.rss",
"https://ru.investing.com/rss/news_477.rss",
"https://ru.investing.com/rss/news_11.rss",
"https://ru.investing.com/rss/news_95.rss",
"https://ru.investing.com/rss/news_14.rss",
"https://ru.investing.com/rss/news_285.rss",
"https://ru.investing.com/rss/news_25.rss"

```
python3.10/site-packages/rss_parser/_parser.py", line 88, in parse
    "title": main_soup.title.text,
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by dhvcc** [comment]
Hi, let me take a look at it :eyes:

**Comment by dhvcc** [comment]
I'm rewriting the current implementation to be better coded, more flexible and more usable, you may have to wait for it. If this is urgent feel free to fork and implement any workaround for it

**Comment by DimaDDM** [comment]
> I'm rewriting the current implementation to be better coded, more flexible and more usable, you may have to wait for it. If this is urgent feel free to fork and implement any workaround for it

Thank you. I'm waiting for new release. Happy New Year 🥳 🎄

**Comment by dhvcc** [comment]
@DimaDDM Thank you :) you too have a nice one 🎉

**Comment by dhvcc** [comment]
Hi its been a long time, but I'm kind of stuck figuring out what to do with models. Right now I'm using pydantic and I might need to create not-so-user-friendly dynamic interface to account for tag attributes that can be assigned in RSS. I'm also thinking of using dataclasses and dataclass wizard, not sure. Long story short I don't have much time and stuck here right now. I might just finish this release using a working solution though, but wanted to investigate possibilities of using different libraries before pushing to master

Current draft code is on v2 branch

**Comment by DimaDDM** [comment]
> Hi its been a long time, but I'm kind of stuck figuring out what to do with models. Right now I'm using pydantic and I might need to create not-so-user-friendly dynamic interface to account for tag attributes that can be assigned in RSS. I'm also thinking of using dataclasses and dataclass wizard, not sure. Long story short I don't have much time and stuck here right now. I might just finish this release using a working solution though, but wanted to investigate possibilities of using different libraries before pushing to master
> 
> Current draft code is on v2 branch

What about new version with working solution marked as alpha or beta label?

**Comment by dhvcc** [comment]
@DimaDDM yeah, I might deploy it as beta, but it'll still require docs and a small cleanup, so I think I'll only be able to do it on weekends
