### ISSUE TITLE
guid attribute is not parsed

### ISSUE THREAD

**Issue by Sait-Nuri** [dhvcc/rss-parser#39]
Hi 

I have spotted that guid attribute is not parsed by the parser. I need it beacuse most of  the time includes a unique identifier. For example: 

`<guid isPermaLink="false">/node/18150</guid>`

It would be good if that feature added to the library. Then I will depend on this library for my projects :)

**Comment by dhvcc** [comment]
Hi, @Sait-Nuri , thanks for using the library. I'm working on a rework using Pydantic and it's nearly finished, just some unittests left and docs. It's currently on `v2` branch, but there's a mess of commits and comments 😅 
It was supposed to come out much earlier, but I'm planning on finishing it this week for sure. I'll post an update to this issue when it's somewhat usable.
Important note is that you'll be able to customize and extend default schemas to suit your purposes

**Comment by dhvcc** [comment]
You can take a look at the pr https://github.com/dhvcc/rss-parser/pull/40, now, with pydantic, there's a wasy of parsing xml attributes (it's working already) and there's a test RSS samle with GUID attributes making sure they're working right. It's not finished yet though, there's still Parser class rework that needs to be done, as well as docs
https://github.com/dhvcc/rss-parser/blob/65a4e5c8ebdb1326309071aae9eddead70ec140c/rss_parser/models/item.py#L33

**Comment by Sait-Nuri** [comment]
Thanks for you effords :) will you push that change to master ?

**Comment by dhvcc** [comment]
Surely will do when I finish. There's been **a lot** of coding/scraping and refactoring in this version. Trying to create a solid base with good code to not refactor it in year 😅

**Comment by dhvcc** [comment]
Hi, @Sait-Nuri , can you check out readme at V2 branch https://github.com/dhvcc/rss-parser/tree/v2, and tell me if everything's clear here? Especially the `Tag` portion. Seems like the release is ready, but curious if docs are clear enough, thanks!

**Comment by dhvcc** [comment]
[V1](https://github.com/dhvcc/rss-parser) has been released and it now parses all of the attributes you have, please, check it out. Closing this for now
