### ISSUE TITLE
Lib still broken for Python 3.8+

### ISSUE THREAD

**Issue by GrenderG** [dhvcc/rss-parser#45]
After https://github.com/dhvcc/rss-parser/commit/699c3aa80f45224324d2fa0d07dfd82cf9c1aee2 the following error appears:
`TypeError: <class 'rss_parser.models.types.only_list.OnlyList'> is not a generic class`

**Comment by dhvcc** [comment]
Hey, sorry this got delayed, but this commit wasn't deployed as it failed the tests. I'm not sure how to achieve the same functionality in 3.8. I might've written something like this some time ago, but I don't remember how I did it. I'll revisit it after a break from work

**Comment by dhvcc** [comment]
There's no good way of supporting 3.8 and this functionality without using hacks or not very clean code. I try to keep this library simple
Python 3.8 is now retired, see [#v1.2.1](https://github.com/dhvcc/rss-parser/releases/tag/v1.2.1)
Closing for now, feel free to reopen if not satisfactory
