### ISSUE TITLE
Invalid tags parsing

### ISSUE THREAD

**Issue by DimaDDM** [dhvcc/rss-parser#49]
Hello. I have encountered a serious error in the library, which does not allow to parse some RSS sources correctly. For example, [here ](http://static.feed.rbc.ru/rbc/logical/footer/news.rss) the tags contain two <link> entries and the parser throws an error when trying to read the elements.

`channel -> content -> item -> 9 -> content -> link -> content
  str type expected (type=type_error.str)`

`channel -> content -> item -> 0 -> content -> enclosure -> content
  str type expected (type=type_error.str)`

Can you fix it? Thank you!

**Comment by dhvcc** [comment]
Hi, thanks for using the library. I'll do this in the morning, as it's a bit late for me now. I'll update you on the solution here

**Comment by dhvcc** [comment]
@DimaDDM Hi, sorry for the late response, just found some time to look at this
It in fact seems like the issue in original typings. However, I can't reproduce the <link> issue, seems the feed has changed. I will update the type for `enclosure`

If this happens in the future - you cna raise another issue or comment on this one. Meanwhile, you are able to [customize the types yourself](https://github.com/dhvcc/rss-parser?tab=readme-ov-file#overriding-schema), for example, when the feed is non standart

**Comment by DimaDDM** [comment]
> @DimaDDM Hi, sorry for the late response, just found some time to look at this It in fact seems like the issue in original typings. However, I can't reproduce the issue, seems the feed has changed. I will update the type for `enclosure`
> 
> If this happens in the future - you cna raise another issue or comment on this one. Meanwhile, you are able to [customize the types yourself](https://github.com/dhvcc/rss-parser?tab=readme-ov-file#overriding-schema), for example, when the feed is non standart

Hello. Thank you. Can you try this [link](https://www.vedomosti.ru/rss/rubric/economics), for example? Same issue right now. Also [another crash here](https://feeds.bloomberg.com/technology/news.rss)

**Comment by dhvcc** [comment]
@DimaDDM hey, just an update. Doing a bit of a deeper dive into which elements might break when empty (but allowed per spec). The change is going to be a bit bigger

For now, I recommend using `Optional[Tag[Optional[str]]]` for those elements (trust me, it makes sense haha)
